name: Test GitHub Runners

on: push

jobs:
  hello_world_job:
    name: Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build Project
        run: ./gradlew build

      - name: Run Desktop Tests
        run: ./gradlew composeApp:desktopTest

      - name: Run Android Unit Tests
        run: ./gradlew composeApp:testDebugUnitTest

      - name: Create Test Summary
        uses: test-summary/action@v2
        with:
          paths: '**/test-results/**/*.xml'
          show: "pass, fail, skip"
