name: Test GitHub Runners

on: push

jobs:
  hello_world_job:
    name: Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build Project
        run: ./gradlew build
