name: Test GitHub Runners

on: push

jobs:
  hello_world_job:
    name: Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build Project
        run: ./gradlew build

      - name: Run Desktop Tests
        run: ./gradlew composeApp:desktopTest

      - name: Run Android Unit Tests
        run: ./gradlew composeApp:testDebugUnitTest

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android Emulator Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew connectedAndroidTest
          arch: x86_64

      - name: Create Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            '**/*est-results/**/*.xml'
          show: "pass, fail, skip"

