name: Test GitHub Runners

on:
  push:
    branches:
      - main  # Set this to your default branch if it's not 'main' jobs:
jobs:
  hello_world_job:
    name: Hello World
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, GitHub Actions!"
